rm lib/ui_web/controllers/contact_controller.ex
rm lib/ui_web/templates/contact/edit.html.eex
rm lib/ui_web/templates/contact/form.html.eex
rm lib/ui_web/templates/contact/index.html.eex
rm lib/ui_web/templates/contact/new.html.eex
rm lib/ui_web/templates/contact/show.html.eex
rm lib/ui_web/views/contact_view.ex
rm test/ui_web/controllers/contact_controller_test.exs
rm lib/ui/repository/contact.ex
rm priv/repo/migrations/20191115215554_create_contacts.exs
rm lib/ui/repository.ex
rm lib/ui/repository.ex
rm test/ui/repository_test.exs
rm test/ui/repository_test.exs
